
package dams.QUEServerGenerated;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import dams.model.AppointmentType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "QUEHospitalServer", targetNamespace = "http://server.dams/")
public interface QUEHospitalServer {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "quebecAppointmentScheduleOfPatientId", targetNamespace = "http://server.dams/", className = "dams.server.QuebecAppointmentScheduleOfPatientId")
	@ResponseWrapper(localName = "quebecAppointmentScheduleOfPatientIdResponse", targetNamespace = "http://server.dams/", className = "dams.server.QuebecAppointmentScheduleOfPatientIdResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/quebecAppointmentScheduleOfPatientIdRequest", output = "http://server.dams/QUEHospitalServer/quebecAppointmentScheduleOfPatientIdResponse")
	public String quebecAppointmentScheduleOfPatientId(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "quebecCancelAppointmentOfPatientId", targetNamespace = "http://server.dams/", className = "dams.server.QuebecCancelAppointmentOfPatientId")
	@ResponseWrapper(localName = "quebecCancelAppointmentOfPatientIdResponse", targetNamespace = "http://server.dams/", className = "dams.server.QuebecCancelAppointmentOfPatientIdResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/quebecCancelAppointmentOfPatientIdRequest", output = "http://server.dams/QUEHospitalServer/quebecCancelAppointmentOfPatientIdResponse")
	public String quebecCancelAppointmentOfPatientId(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "quebecBookAppointment", targetNamespace = "http://server.dams/", className = "dams.server.QuebecBookAppointment")
	@ResponseWrapper(localName = "quebecBookAppointmentResponse", targetNamespace = "http://server.dams/", className = "dams.server.QuebecBookAppointmentResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/quebecBookAppointmentRequest", output = "http://server.dams/QUEHospitalServer/quebecBookAppointmentResponse")
	public String quebecBookAppointment(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") AppointmentType arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "quebecListAppointmenOfType", targetNamespace = "http://server.dams/", className = "dams.server.QuebecListAppointmenOfType")
	@ResponseWrapper(localName = "quebecListAppointmenOfTypeResponse", targetNamespace = "http://server.dams/", className = "dams.server.QuebecListAppointmenOfTypeResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/quebecListAppointmenOfTypeRequest", output = "http://server.dams/QUEHospitalServer/quebecListAppointmenOfTypeResponse")
	public String quebecListAppointmenOfType(@WebParam(name = "arg0", targetNamespace = "") AppointmentType arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "removeAppointmentQUE", targetNamespace = "http://server.dams/", className = "dams.server.RemoveAppointmentQUE")
	@ResponseWrapper(localName = "removeAppointmentQUEResponse", targetNamespace = "http://server.dams/", className = "dams.server.RemoveAppointmentQUEResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/removeAppointmentQUERequest", output = "http://server.dams/QUEHospitalServer/removeAppointmentQUEResponse")
	public String removeAppointmentQUE(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") AppointmentType arg1);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg4
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "swapAppointmentQUE", targetNamespace = "http://server.dams/", className = "dams.server.SwapAppointmentQUE")
	@ResponseWrapper(localName = "swapAppointmentQUEResponse", targetNamespace = "http://server.dams/", className = "dams.server.SwapAppointmentQUEResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/swapAppointmentQUERequest", output = "http://server.dams/QUEHospitalServer/swapAppointmentQUEResponse")
	public String swapAppointmentQUE(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") AppointmentType arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") AppointmentType arg4);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "bookAppointmentQUE", targetNamespace = "http://server.dams/", className = "dams.server.BookAppointmentQUE")
	@ResponseWrapper(localName = "bookAppointmentQUEResponse", targetNamespace = "http://server.dams/", className = "dams.server.BookAppointmentQUEResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/bookAppointmentQUERequest", output = "http://server.dams/QUEHospitalServer/bookAppointmentQUEResponse")
	public String bookAppointmentQUE(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") AppointmentType arg2);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "addAppointmentQUE", targetNamespace = "http://server.dams/", className = "dams.server.AddAppointmentQUE")
	@ResponseWrapper(localName = "addAppointmentQUEResponse", targetNamespace = "http://server.dams/", className = "dams.server.AddAppointmentQUEResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/addAppointmentQUERequest", output = "http://server.dams/QUEHospitalServer/addAppointmentQUEResponse")
	public String addAppointmentQUE(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") AppointmentType arg1,
			@WebParam(name = "arg2", targetNamespace = "") int arg2);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg4
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "addRecordIntoLogFileQUE", targetNamespace = "http://server.dams/", className = "dams.server.AddRecordIntoLogFileQUE")
	@ResponseWrapper(localName = "addRecordIntoLogFileQUEResponse", targetNamespace = "http://server.dams/", className = "dams.server.AddRecordIntoLogFileQUEResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/addRecordIntoLogFileQUERequest", output = "http://server.dams/QUEHospitalServer/addRecordIntoLogFileQUEResponse")
	public void addRecordIntoLogFileQUE(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<String> arg2,
			@WebParam(name = "arg3", targetNamespace = "") boolean arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listAppointmentAvailabilityQUE", targetNamespace = "http://server.dams/", className = "dams.server.ListAppointmentAvailabilityQUE")
	@ResponseWrapper(localName = "listAppointmentAvailabilityQUEResponse", targetNamespace = "http://server.dams/", className = "dams.server.ListAppointmentAvailabilityQUEResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/listAppointmentAvailabilityQUERequest", output = "http://server.dams/QUEHospitalServer/listAppointmentAvailabilityQUEResponse")
	public String listAppointmentAvailabilityQUE(@WebParam(name = "arg0", targetNamespace = "") AppointmentType arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "cancelAppointmentQUE", targetNamespace = "http://server.dams/", className = "dams.server.CancelAppointmentQUE")
	@ResponseWrapper(localName = "cancelAppointmentQUEResponse", targetNamespace = "http://server.dams/", className = "dams.server.CancelAppointmentQUEResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/cancelAppointmentQUERequest", output = "http://server.dams/QUEHospitalServer/cancelAppointmentQUEResponse")
	public String cancelAppointmentQUE(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAppointmentScheduleQUE", targetNamespace = "http://server.dams/", className = "dams.server.GetAppointmentScheduleQUE")
	@ResponseWrapper(localName = "getAppointmentScheduleQUEResponse", targetNamespace = "http://server.dams/", className = "dams.server.GetAppointmentScheduleQUEResponse")
	@Action(input = "http://server.dams/QUEHospitalServer/getAppointmentScheduleQUERequest", output = "http://server.dams/QUEHospitalServer/getAppointmentScheduleQUEResponse")
	public String getAppointmentScheduleQUE(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
